[package]
name = "lz4"
description = "Lz4 compression for Rust"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"

[features]
alloc = []

[dependencies]

[dev-dependencies]
base64 = "0.13.0"
